k8s deployment modifications, Build-time LLM env var
defenseunicorns/doug-translate pull request #34
Opened 2023-10-30 14:03 UTC by justinthelaw

* Confirmed K3D + DUBBD + LFAI (Go API) + Whisper + CTransformers integration working
* Groundwork for CTransformers + Batched Summary
* Dynamic ORIGIN value based on full domain, defaulting to Istio Tenant Gateway's external IP address
* Summarization LLM switching at deploy time using env vars

2023-10-30 16:29 UTC, CollectiveUnicorn commented
Does the docker deployment work properly with purely using the `.env` file?

2023-10-30 18:26 UTC, justinthelaw commented
> Does the docker deployment work properly with purely using the `.env` file?

Yeah, the dotenv is mostly being used for pulling in the environment variables being pulled in from the Zarf build and deploy. In `openai.ts` uses one of those variable to set the leapfrogai base url, and I decided to also use that to tell doug-translate which model to use for summarization. We could just add to the docker command to use the .env file using the env flag `--env-file .env` during Docker run?

2023-10-30 18:34 UTC, Noxsios requested changes

2023-10-30 18:34 UTC, Noxsios commented on manifests/namespace.yaml
```yaml
          - cmd: ./zarf tools kubectl label namespace doug-translate istio-injection=enabled
```

can safely be removed from the `zarf.yaml` with this ns addition

2023-10-30 23:55 UTC, CollectiveUnicorn approved these changes

2023-10-31 14:23 UTC, justinthelaw commented on manifests/namespace.yaml
Yeah, I saw that in the zarf.yaml, but it wasn't quite working for me at first. Let me test again to make sure! And if it does, I'll modify this PR.

2023-10-31 18:06 UTC, CollectiveUnicorn commented on zarf.yaml
The namespace way I think is objectively better, I think the suggestion was to remove the line `./zarf tools kubectl label namespace doug-translate istio-injection=enabled` from the zarf.yaml to use what you added instead.

2023-10-31 18:19 UTC, justinthelaw commented on zarf.yaml
Ah okay, I'll revert haha

2023-10-31 22:46 UTC, CollectiveUnicorn approved these changes

2023-11-01 17:07 UTC, Noxsios approved these changes

2023-11-01 17:15 UTC, merged