Download buttons
defenseunicorns/doug-translate pull request #44
Opened 2023-11-02 02:59 UTC by Noxsios

Closes #41

2023-11-02 04:04 UTC, Noxsios commented
I did as much verification / testing as I could w/o access to LFAI, please test the 2 new download buttons when you can.

@justinthelaw @CollectiveUnicorn

2023-11-02 14:26 UTC, justinthelaw requested changes
Overall looks great! I think the change to memory should be addressed in a different PR (for separation of concerns purposes), which I can push today on a branch I was on.

2023-11-02 14:26 UTC, justinthelaw commented on manifests/deploy.yaml
> +              memory: "800Mi"
I think for max memory, just to be safe, we should lean towards 1.5Gi. Reason being, I tested a 1 hour audio and it took up nearly 1Gi of RAM (an OpenAI library issue), so I upped the container memory limit accordingly. I still need to test on a larger sample size, but the short term fix is to just allocate more memory. It's possible some users will need to transcribe longer meetings or possibly concurrently process multiple shorter meetings.

In the long term, we may want to do our own client-side chunking and reassembly of the audio. For now, I think we just stick with more memory limit while we think of a better solution.

2023-11-06 18:02 UTC, CollectiveUnicorn approved these changes

2023-11-06 18:26 UTC, CollectiveUnicorn requested changes
I'm getting a weird artifact on the page with a large transcript
![Uploading Screenshot 2023-11-06 at 10.25.37 AM.png…]()

2023-11-06 19:19 UTC, justinthelaw commented
@Noxsios @CollectiveUnicorn I also get the same visual artifact. 
![image](https://github.com/defenseunicorns/doug-translate/assets/81255462/05b4ef0b-4036-4e46-bb94-cef3b11a376a)

2023-11-08 19:21 UTC, justinthelaw approved these changes
Looks good to me! I think with the time constraint, this is good enough.

2023-11-08 20:23 UTC, CollectiveUnicorn approved these changes

2023-11-08 20:25 UTC, merged