Transcript Batching and Improved Prompting
defenseunicorns/doug-translate pull request #55
Opened 2023-11-08 22:29 UTC by justinthelaw

2023-11-09 23:48 UTC, CollectiveUnicorn approved these changes

2023-11-10 00:58 UTC, Noxsios requested changes

2023-11-10 00:58 UTC, Noxsios commented on src/lib/tokenizer.ts
> +    throw new Error(message);
what causes this `catch` to trigger?

2023-11-10 00:58 UTC, Noxsios commented on src/routes/upload/+page.server.ts
> +    const transcriptionFile = `${TEMPORARY_DIRECTORY}/${uid}.txt`;
avoid hardcoding paths w/ `/`s, use `path.join` instead for cross OS support

2023-11-10 00:58 UTC, Noxsios commented on src/routes/upload/+page.server.ts
> +    const uid = formData.get("uid") as File;
I believe `uid` is a `string`

2023-11-10 00:58 UTC, Noxsios commented on src/routes/upload/+page.svelte
> +  let errorMessage: Error | null = null;
since this is of the type `Error` not `string`, it is better to call this var `err`

2023-11-10 00:58 UTC, Noxsios commented on src/routes/upload/+page.svelte
> +    // }
remove commented code if unused

2023-11-10 00:58 UTC, Noxsios commented on src/routes/upload/+page.svelte
> +          <p style="white-space: pre-line;">
This is `class="whitespace-pre-line"` per: https://tailwindcss.com/docs/whitespace

2023-11-10 00:58 UTC, Noxsios commented on zarf.yaml
> +      - ghcr.io/defenseunicorns/doug-translate:0.1.0
this does not match the `README` or `hack/build.sh`

2023-11-10 13:12 UTC, justinthelaw commented on src/routes/upload/+page.svelte
> +  let errorMessage: Error | null = null;
Yeah true - when I was doing merge conflicts, it was originally just a string so I accidentally merged it this way.

2023-11-10 13:13 UTC, justinthelaw commented on src/lib/tokenizer.ts
> +    throw new Error(message);
At first I had out in the part where things were tokenized here and never got around to removing the try-catch. Will remove!

2023-11-10 13:14 UTC, justinthelaw commented on src/routes/upload/+page.server.ts
> +    const transcriptionFile = `${TEMPORARY_DIRECTORY}/${uid}.txt`;
Was originally proof of concept, so forgot to come back and clean-up before transitioning from local dev to cluster testing.

2023-11-10 13:16 UTC, justinthelaw commented on src/routes/upload/+page.svelte
> +          <p style="white-space: pre-line;">
Ah yeah, my bad, will change that too.

2023-11-10 13:19 UTC, justinthelaw commented on src/routes/upload/+page.server.ts
> +    const uid = formData.get("uid") as File;
Yes, and filename too. I must've copied over the original audio file line of code and didn't change the "as type" part

2023-11-10 20:27 UTC, justinthelaw commented on src/routes/upload/+page.server.ts
> +    const transcriptionFile = `${TEMPORARY_DIRECTORY}/${uid}.txt`;
Turns out the transcription batching that @CollectiveUnicorn was implementing changed the type to File instead of string depending on the file size situation. Something isn't quite working on the most up-to-date commits so will need to investigate that and this typing scenario.

Last working commit was: 8356627100298bc20a143d8965cfaabc55ab4b23 "Updates the whisper call to be non-blocking"

2023-11-10 23:47 UTC, justinthelaw commented on src/routes/transcription/+server.ts
@CollectiveUnicorn I am a little confused about the purpose of this portion. Is the main purpose of this, and the frontned function with a 5 second timeout, to basically keep the connection alive? Wouldn't a simple healthcheck just looking for UID be enough, returning a status 200 instead of the whole transcript again?

2023-11-11 00:39 UTC, CollectiveUnicorn commented on src/routes/transcription/+server.ts
The backend was modified to not return the transcript back when submitting the form. The form triggers the start of the transcription then immediately return with information like the uid. That information is used to poll the backend in 5 second intervals for the finished transcription. The frontend asks the `transcription/` endpoint to check to see if the transcription has finished. If the endpoint is able to successfully retrieve the file it returns it and "Complete". If not, it just returns "Incomplete". The complete and incomplete thing could probably be removed in favor of something different like checking for the element in the json or using a different status code, but this was just the implementation I came up with last night. It works, but could be better.

2023-11-11 00:41 UTC, CollectiveUnicorn commented on src/routes/transcription/+server.ts
This allows the transcription to take as long as it needs to, so that it never hit the timeout that I was seeing with some of the longer multi-hour long transcriptions. Effectively just starting a job on the backend and checking back to see if its done.

2023-11-11 21:35 UTC, CollectiveUnicorn submitted a review, later dismissed

2023-11-12 20:00 UTC, Noxsios requested changes

2023-11-12 20:00 UTC, Noxsios commented on src/routes/upload/+page.svelte
> +    const transcript = writable("")
I do not see a reason why this is a Svelte store and not simply a `let` variable, it is local only state, so there is no need for it to be a store

2023-11-12 22:50 UTC, CollectiveUnicorn commented on src/routes/upload/+page.server.ts
> +    openai.audio.transcriptions
It is the intended behavior, the await was removed due to the errors that occurred when multi-hour long files are uploaded. As the time it takes for Whisper to turn a response to the `POST` request becomes a problem. The `retrieveTranscription` function on the frontend polls the transcription `endpoint` in 5 second intervals to check for the file's creation when the user uploads an audio file. The loading screen persists on the frontend until the file is created. As the loading screen is only removed when the `Complete` response is returned.

2023-11-12 22:55 UTC, CollectiveUnicorn commented on src/routes/upload/+page.server.ts
> +    await unlink(transcriptionFile);
As is, the `clearTmp` function runs on every upload whether the summary is being done or not.

2023-11-12 23:30 UTC, CollectiveUnicorn commented on src/routes/upload/+page.svelte
> +    const transcript = writable("")
Should be good now, I made it a let instead of a svelte store.

2023-11-12 23:31 UTC, CollectiveUnicorn commented on src/routes/transcription/+server.ts
> +  );
Changed this to use the json function from `@sveltejs/kit`

2023-11-13 00:49 UTC, Noxsios approved these changes
just needs `npm run format`

2023-11-13 01:10 UTC, CollectiveUnicorn approved these changes

2023-11-13 01:19 UTC, merged