Updates timers, hides dev info, and explicitly sets the default timeout
defenseunicorns/doug-translate pull request #88
Opened 2023-11-27 18:08 UTC by CollectiveUnicorn

- Separates summarization and transcription timers
- Hides models and shrinks info on help page
- Adds 60 minute default timeout to openai requests to facilitate large audio and video file uploads

2023-11-27 19:17 UTC, justinthelaw approved these changes
Worked great at CENTCOM!

2023-11-27 20:09 UTC, Noxsios requested changes

2023-11-27 22:47 UTC, CollectiveUnicorn commented on src/routes/upload/+page.svelte
> +              summarizationTimerStart = Date.now();
I believe that's intentional @justinthelaw right? So that every time the summary is triggered the value is based on the time from the start of the summary.

2023-11-27 22:54 UTC, justinthelaw commented on src/routes/upload/+page.svelte
> +              summarizationTimerStart = Date.now();
Yes, this button only shows up once in the workflow - when the transcription ends and the user requests a summary via this button. This button never shows up again from there. 

There is a future where we could let the user ask for another summary just to get multiple choices, but that's a different story/issue for another day!

2023-11-27 23:33 UTC, CollectiveUnicorn commented on src/routes/+layout.svelte
> +      <li class="hidden"><a href="/models">Models</a></li>
Leaving the route, its genuinely useful for debugging even if there's no menu item to it. But I have removed the menu item.

2023-11-27 23:33 UTC, CollectiveUnicorn commented on src/routes/upload/+page.svelte
> +          ).toFixed(2)} minutes</code
Moved to helper.ts and new `minutes` function

2023-11-27 23:34 UTC, CollectiveUnicorn commented on src/routes/help/+page.svelte
> +  >
Deleted

2023-11-27 23:36 UTC, CollectiveUnicorn commented on src/routes/upload/+page.svelte
> +          ).toFixed(2)} minutes</code
Now `minutesElapsed` for clarity

2023-11-27 23:46 UTC, CollectiveUnicorn commented on src/routes/upload/+page.svelte
> +  $: retrieveTranscription(form?.upload?.uid);
This won't work if its not a function, as the `setTimeout(retrieveTranscription, 5000, uid);` contained in `retrieveTranscription` is a recursive function call. Ideally we wouldn't need to do this but I was unable to capture the uid change consistently in other portions of the form submission lifecycle.

2023-11-28 18:43 UTC, Noxsios approved these changes

2023-11-28 18:44 UTC, merged